<#
.SYNOPSIS
    Fetch tor.exe + obfs4 (lyrebird) from an OFFICIAL Tor Expert Bundle, verify
    the download hash, and stage them under third_party\tor.

.DESCRIPTION
    Policy (see third_party\README.md): third-party binaries only from official
    releases, verified by hash. This script:
      1. Downloads the Tor Expert Bundle .tar.gz you point it at.
      2. Verifies it against the SHA-256 you provide (from the official site).
      3. Extracts tor.exe and the obfs4 transport (lyrebird/obfs4proxy).
      4. Writes third_party\tor\hashes.txt pinning tor.exe's SHA-256.

    Get the bundle + its checksum from:
        https://www.torproject.org/download/tor/  (Windows Expert Bundle, x86_64)
    Checksums / signatures are published alongside each file.

.PARAMETER Url
    Direct URL to the official Tor Expert Bundle (.tar.gz) for Windows x86_64.

.PARAMETER Sha256
    Expected SHA-256 of that archive (from the official checksum file).

.EXAMPLE
    .\scripts\fetch-tor.ps1 -Url "https://archive.torproject.org/.../tor-expert-bundle-windows-x86_64-<ver>.tar.gz" -Sha256 "ABC123..."
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string] $Url,
    [Parameter(Mandatory = $true)] [string] $Sha256
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$destDir  = Join-Path $repoRoot 'third_party\tor'
$tmp      = Join-Path $env:TEMP ("tor_" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $tmp, $destDir | Out-Null

try {
    $archive = Join-Path $tmp 'tor.tar.gz'
    Write-Host "Downloading $Url ..."
    Invoke-WebRequest -Uri $Url -OutFile $archive -UseBasicParsing

    $actual = (Get-FileHash $archive -Algorithm SHA256).Hash
    if ($actual -ne $Sha256.Trim().ToUpper()) {
        throw "Download SHA-256 mismatch.`n  expected: $Sha256`n  actual:   $actual`nAborting."
    }
    Write-Host "Archive hash verified." -ForegroundColor Green

    # Windows 10+ ships bsdtar as tar.exe, which handles .tar.gz.
    tar -xzf $archive -C $tmp
    if ($LASTEXITCODE -ne 0) { throw "tar extraction failed (exit $LASTEXITCODE)." }

    $tor = Get-ChildItem -Path $tmp -Recurse -File -Filter 'tor.exe' | Select-Object -First 1
    if (-not $tor) { throw "tor.exe not found inside the bundle." }
    Copy-Item $tor.FullName (Join-Path $destDir 'tor.exe') -Force
    Write-Host "  staged tor.exe"

    # obfs4 transport: newer bundles ship 'lyrebird.exe', older 'obfs4proxy.exe'.
    $obfs = Get-ChildItem -Path $tmp -Recurse -File |
            Where-Object { $_.Name -in @('lyrebird.exe', 'obfs4proxy.exe') } |
            Select-Object -First 1
    if ($obfs) {
        Copy-Item $obfs.FullName (Join-Path $destDir $obfs.Name) -Force
        Write-Host "  staged $($obfs.Name)"
    } else {
        Write-Warning "obfs4 transport (lyrebird/obfs4proxy) not found - obfs4 bridges will not work."
    }

    # Copy any adjacent DLLs tor.exe needs (some bundles ship them beside tor.exe).
    Get-ChildItem -Path $tor.Directory.FullName -File -Filter '*.dll' -ErrorAction SilentlyContinue |
        ForEach-Object { Copy-Item $_.FullName (Join-Path $destDir $_.Name) -Force }

    $torHash = (Get-FileHash (Join-Path $destDir 'tor.exe') -Algorithm SHA256).Hash
    @(
        "# SHA-256 pins for Tor binaries. Generated by fetch-tor.ps1.",
        "$torHash  tor.exe"
    ) | Set-Content -Path (Join-Path $destDir 'hashes.txt') -Encoding utf8

    Write-Host "`nDone. Staged in $destDir" -ForegroundColor Green
    Write-Host "tor.exe SHA-256 pinned: $torHash"
}
finally {
    Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
}
